import { useState } from "react";
import type { FollowUpAction, Severity } from "./lib/vista-db";
type Entry = { text: string; assignee?: string; dueDate?: string; severity: Severity };
export default function ActionSplit({ action, onSave }: { action: FollowUpAction; onSave: (entries: Entry[]) => Promise<boolean> }) {
  const [entries, setEntries] = useState<Entry[]>([{ text: action.text, assignee: action.assignee, dueDate: action.dueDate, severity: action.severity }, { text: "", severity: action.severity }]);
  const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const change = (index: number, changes: Partial<Entry>) => setEntries((items) => items.map((item, i) => i === index ? { ...item, ...changes } : item));
  return <form className="action-split" onSubmit={async (event) => { event.preventDefault(); setBusy(true); setError(""); try { if (!await onSave(entries)) setError("Enregistrement impossible. Vos saisies restent affichées."); } finally { setBusy(false); } }}>
    <h2>Scinder une action</h2><p>Décrivez chaque demande séparément. Elles resteront liées au même constat, à sa voix et à ses photos ; l’original n’est pas réécrit.</p>
    <blockquote className="source-quote">{action.text}</blockquote><fieldset disabled={busy}>{entries.map((entry, index) => <article key={index} className="split-entry"><h3>Action {index + 1}</h3><label className="form-field">Description de l’action {index + 1}<textarea aria-label={`Description de l’action ${index + 1}`} required rows={3} value={entry.text} onChange={(event) => change(index, { text: event.target.value })} /></label><label className="form-field">Entreprise / intervenant {index + 1}<input value={entry.assignee ?? ""} onChange={(event) => change(index, { assignee: event.target.value })} /></label><label className="form-field">Échéance de l’action {index + 1}<input type="date" value={entry.dueDate ?? ""} onChange={(event) => change(index, { dueDate: event.target.value })} /></label><label className="form-field">Urgence de l’action {index + 1}<select aria-label={`Urgence de l’action ${index + 1}`} value={entry.severity} onChange={(event) => change(index, { severity: event.target.value as Severity })}><option value="urgent">Urgent</option><option value="planned">À planifier</option><option value="info">Pour info</option></select></label>{entries.length > 2 && <button type="button" className="text-button" onClick={() => setEntries((items) => items.filter((_, i) => i !== index))}>Retirer l’action {index + 1}</button>}</article>)}<button type="button" className="secondary-action add-zone" disabled={entries.length >= 20} onClick={() => setEntries((items) => [...items, { text: "", severity: action.severity }])}>Ajouter une action distincte</button>{error && <p role="alert">{error}</p>}<button className="primary-action">Enregistrer les actions séparées</button></fieldset>
  </form>;
}
